version: '3.8' #3.7

services:
  db:
    image: mysql:9.5.0
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "5175:3306"
    networks:
      - padelup_network
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password

  phpmyadmin:
    image: phpmyadmin:5.2.3
    ports:
      - "5174:80"
    networks:
      - padelup_network
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_root_password
    depends_on:
      - db

networks:
  padelup_network:
    driver: bridge