services:
  frontend:
    container_name: padelup_frontend
    build:
      context: ./padelup
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - padelup_network
    volumes:
    - ./padelup:/app
    - padelup_node_modules:/app/node_modules

networks:
  padelup_network:
    driver: bridge

volumes:
  padelup_node_modules: