services:
  db:
    image: mysql:9.5.0
    container_name: padelup_BD
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./padelup.sql:/docker-entrypoint-initdb.d/padelup.sql:ro
    networks:
      - db_network
    healthcheck:
      test: [ "CMD-SHELL", "mysql -u root -p${MYSQL_ROOT_PASSWORD} -D ${MYSQL_DATABASE} -e 'SHOW TABLES;'" ]
      interval: 5s
      timeout: 5s
      retries: 30
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  backend:
    build:
      context: ./backend
    container_name: padelup_backend
    ports:
      - "5176:5000"
    networks:
      - padelup_network
      - db_network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306 # 5175?
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:5.2.3
    container_name: padelup_phpmyadmin
    ports:
      - "5174:80"
    networks:
      - padelup_network
      - db_network
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

networks:
  padelup_network:
    driver: bridge
  db_network:
    internal: true
