services:
  db:
    image: mysql:9.5.0
    container_name: padelup_BD
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./padelup.sql:/docker-entrypoint-initdb.d/padelup.sql:ro
    ports:
      - "5175:3306"
    networks:
      - db_network
    healthcheck:
      test: [ "CMD-SHELL", "mysql -u root -p${MYSQL_ROOT_PASSWORD} -D ${MYSQL_DATABASE} -e 'SHOW TABLES;'" ]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  backend:
    build:
      context: ./backend
    container_name: padelup_backend
    ports:
      - "5176:5000"
    volumes:
      - ./backend:/app
    networks:
      - padelup_network
      - db_network
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306 # 5175?
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      HASH_KEY: ${HASH_KEY}
  frontend:
    build:
      context: ./padelup
      dockerfile: Dockerfile
    container_name: padelup_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./padelup/src:/app/src
      - ./padelup/public:/app/public
      - ./padelup/index.html:/app/index.html
    networks:
      - padelup_network
    depends_on:
      - backend
    restart: on-failure
    environment:
      VITE_API_URL: ${VITE_API_URL}
  phpmyadmin:
    image: phpmyadmin:5.2.3
    container_name: padelup_phpmyadmin
    ports:
      - "5174:80"
    networks:
      - padelup_network
      - db_network
    restart: on-failure
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

networks:
  padelup_network:
    driver: bridge
  db_network:
    internal: true
