version: '3.8' #3.7

services:
  db:
    image: mysql:9.5.0
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./padelup.sql:/docker-entrypoint-initdb.d/padelup.sql:ro
    ports:
      - "5175:3306"
    networks:
      - padelup_network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:5.2.3
    ports:
      - "5174:80"
    networks:
      - padelup_network
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

networks:
  padelup_network:
    driver: bridge